import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import meetingsRouter from "./meetings";
import minutesRouter from "./minutes";
import decisionsRouter from "./decisions";
import tasksRouter from "./tasks";
import dashboardRouter from "./dashboard";
import seedRouter from "./seed";
import dtProjectsRouter from "./dt-projects";
import portalRouter from "./portal";
import committeesRouter from "./committees";
import notificationsRouter from "./notifications";
import searchRouter from "./search";
import filtersRouter from "./filters";
import viewsRouter from "./views";
import profileRouter from "./profile";
import settingsRouter from "./settings";
import calendarRouter from "./calendar";
import recurringRouter from "./recurring";
import schedulingRouter from "./scheduling";
import remindersRouter from "./reminders";
import analyticsRouter from "./analytics";
import exportRouter from "./export";
import plansRouter from "./plans";
import appSettingsRouter from "./app-settings";
import { requireAuth } from "../middleware/require-auth";

const router: IRouter = Router();

router.use(healthRouter);
router.use(seedRouter);
router.use(authRouter);
router.use(portalRouter);
router.use(requireAuth);
router.use(usersRouter);
router.use(meetingsRouter);
router.use(minutesRouter);
router.use(decisionsRouter);
router.use(tasksRouter);
router.use(dashboardRouter);
router.use(dtProjectsRouter);
router.use(committeesRouter);
router.use(notificationsRouter);
router.use(searchRouter);
router.use(filtersRouter);
router.use(viewsRouter);
router.use(profileRouter);
router.use(settingsRouter);
router.use(calendarRouter);
router.use(recurringRouter);
router.use(schedulingRouter);
router.use(remindersRouter);
router.use(analyticsRouter);
router.use(exportRouter);
router.use(plansRouter);
router.use(appSettingsRouter);

export default router;
